### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by BroVic** [Godskid89/r_package_nigeria_master_data#13]
What's the vision for this package?

**Comment by Godskid89** [comment]
To make this data available fr everyone using R, I'm also looking forward to putting it on CRAN

in the future, we might also integrate some functions to do geographic data manipulation

**Comment by BroVic** [comment]
Okay, can I request you to clarify the licensing you want for the package? I have a number of contributions to send. I agree: this package is important and needs to be tightened up for CRAN
