### ISSUE TITLE
Data parsing 

### ISSUE THREAD

**Issue by denironyx** [Godskid89/r_package_nigeria_master_data#6]
Hi @Godskid89 , I finally got the time to review this package. I must confess the idea is pretty awesome and I think it will go along way to improve subject expertise analytics for Nigeria data enthusiasts. 

However, here is what I found out. 

# ----- Factories and Industrial Sites Data
```
industrial_sites <- function() {
  #Pull data from eHealth Africa geoserver
  data <- read.csv("https://gis-a.ie.ehealthafrica.org/geoserver/eHA_db/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=eHA_db:sv_factory_sites&outputFormat=csv")
  return(data)
}
```
This will parse the data as a function. Which means, anytime you want to render the data of industiral_sites it will display as industrial_sites() which is a return function. That's not a perfect ways to render data. 

Instead, I went on to create a .rda file that parse the data in form of a data table similar to what you have `nycflight13` packages

**Comment by Godskid89** [comment]
Nice idea. But the issue with using .rda file is that it will be domicile in the package which will make the package heavy and not fit for CRAN rules.

Calling the data as function will make the package lightweight and ensure that the latest data are always pulled directly from the source

**Comment by denironyx** [comment]
Interesting!

The data wouldn't be domicile in the package, it will be generated in the user's laptop when they run the package.

Instead of having the data as a function when you call it, it's converted to .rda file format which with be render as a dataframe. 

There won't be any heavy duty.

**Comment by Godskid89** [comment]
The data is heavy, the .rda files won't even push to git.

You can try it out anyway


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/17/19,
10:17:44 AM

**Comment by denironyx** [comment]
I submitted a pull request. Kindly, review the code and maybe you can make sense out of it.

**Comment by Godskid89** [comment]
I haven't seen your PR
